spring:
  application:
    name: system-monitor
  kafka:
    producer:
      batch-size: 16384
      retries: 0
      buffer-memory: 33554432
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    bootstrap-servers: BJ-HOST-141:9092,BJ-HOST-142:9092
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: bigdata_system_monitor_group
      auto-offset-reset: earliest
      auto-commit-interval: 100
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
server:
  port: 8080

management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: '*'
spring:
    redis:
        cluster:
            max-redirects: 3
            nodes:
            - 10.37.253.42:6481
            - 10.37.253.42:6482
            - 10.37.253.42:6483
            - 10.37.253.42:6484
            - 10.37.253.42:6485
            - 10.37.253.42:6486
        database: 0
        lettuce:
            pool:
                max-active: 20
                max-idle: 10
                max-wait: 6000
                min-idle: 5
        timeout: 1000
