spring:
  application:
    name: system-monitor


  #redis设置
  redis:
    cluster:
      max-redirects: 3
      nodes:
        - redis-cluster-bigdata-01.qiandingyun.com:6378
        - redis-cluster-bigdata-02.qiandingyun.com:6378
        - redis-cluster-bigdata-03.qiandingyun.com:6378
        - redis-cluster-bigdata-04.qiandingyun.com:6378
        - redis-cluster-bigdata-05.qiandingyun.com:6378
        - redis-cluster-bigdata-06.qiandingyun.com:6378
    database: 0
    lettuce:
        pool:
            max-active: 20
            max-idle: 10
            max-wait: 6000
            min-idle: 5
    timeout: 1000


  #kafka对列设置
  kafka:
    producer:
      batch-size: 16384
      retries: 0
      buffer-memory: 33554432
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    bootstrap-servers: BJ-HOST-141:9092,BJ-HOST-142:9092
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: bigdata_system_monitor_group
      auto-offset-reset: earliest
      auto-commit-interval: 100
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer


  #数据源设置
  datasource:
    #连接MySQL
    url: jdbc:mysql://mysql-qddata.qiandingyun.com:3306/ds
    username: ds
    password: 123456!
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8080

management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: '*'


wechart:
   access_token_url: http://dev-qxapi.qdingnet.com/qx/wx/gettoken?type=
   message_send_url: https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token=ACCESS_TOKEN
   agentid: 1000016
